### PR TITLE
Create How do I add multiple books to KyBook3 from Dropbox?

### PR DESCRIPTION
**Pull request by karlic**
kolyvan, could you add this to the FAQs on http://kybook-reader.com/help.html.

I had been adding them to https://github.com/kolyvan/kybook/wiki, but I guess that's the wrong place.

karlic

### CODE REVIEW

**Comment by kolyvan** [comment]
There is no more separate File Browser for new users. It was removed in v0.5.1.
Unfortunately this FAQ will not help new users.

**Comment by karlic** [comment]
Does this mean the only way to import a large number of books is to drag and drop them in iTunes?

Without File Browser I can't connect to Dropbox, is that right?
I can't download more than one book at a time from an OPDS (Calibre), is that right?

**Comment by karlic** [comment]
OK, so it seems that if I turn **_off_** the advanced UI File Browser disappears and there is no way to add Dropbox or other cloud storage. With the advanced UI turned on, the cloud storage options are under File Browser, which presumably is not what non-beta testers see.

**Comment by kolyvan** [comment]
> <i>there is no way to add Dropbox or other cloud storage</i>

Sorry but this it not true.
Certainly you can add any Storage as you wish.

kybook-add-storage-1
kybook-add-storage-2


There is even FAQ about it 
http://kybook-reader.com/faq/2018/09/22/add_shared_folder.html

**Pull request closed without merging**
