### PR TITLE
Create no_undelete.html

### PR DESCRIPTION
**Pull request by karlic**

### CODE REVIEW

**Comment by kolyvan** [comment]
Thank you for your contribution.

**Comment by kolyvan** [comment]
FYI: I think about adding some `Undo delete` feature.
But at first glance it requires lots of work to be done.
There are lots of pitfalls due to synchronization, database use, etc.

**Comment by karlic** [comment]
Could you not just create a folder called Trash and move the files there when the user presses `Delete`? Then just add some code to stop the user creating a folder called Trash and code to the `Delete` routine to really delete files deleted from Trash. You wouldn't need an Undo feature as the user could just move the files back from the Trash folder.

**Comment by kolyvan** [comment]
Unfortunately folder `Trash` absolutely is not enough.
When user presses `Delete a file`, KyBook does  next steps:
1) Deletes a file 
2) Deletes serveral cached/supports files
3) Deletes related records from the database
4) Deletes a user created assets like summary, etc
5) Syncs a deletion event with the KyBook cloud when Synchronization is enabled

For valid undo, must carefuly undoing steps 1,3,4,5. Only step 2 can be skipped. 

For undo step 1, yes, may just move a file into the trash folder. 
But what if deleted file was located on the cloud storage. 
Cloud Storage may or may not has a support for Trash. 
Must download file before deleting to the device to allow undoing when the Cloud Storage does not support undoing? 
Downloading a file before deleting may really be a bad idea since the bandwidth and disc space limtation on the mobile devices.
But and in case of a local file is not so easy. 
What if an user after deletion, moves some files or folders, downloaded new.
What if at a previous path there is other file with the same filename.
Can't replace a new file, may only move from the thrash folder into a previous folder with fixed filename like (ebook_name_1.epub) and must change a filename in the database records from step 3.

For undo step 3, must select and save all deleting records. 
Can't just use `delete from books where`. 
Before deletiion must read and pack deleted records and save them into Trash folder too.

For undo step 4, may just move user's created assets into Trash folder.

Undo step 5 just impossible when deletion was successfully synced to the cloud and other devices.
Only can create a new book's record and sync to the cloud anew, but there are other pitfalls. 

And most likely, there are more pitfalls when I can't imagine ever.

Resume, just moving a deleted file to Trash folder is not enough and is not working in the most cases.

**Pull request merged**
